namespace MC5to7.Services.MadLib
{
    public class MadLibService : IMadLibService
    {

        public string Madness(string adject1, string charaName, string adject2, string noun1, string noun2, string noun3, string color1, string noun4, string adject3, string noun5, string adject4, string onomat1, string adject5, string color2, string noun6, string noun7)
        {
            return $"It was a {adject1} summer day in New New York. Deep within the bowels of the Planet Express building, Fry and {charaName} were were carrying a large and {adject2} box into their delivery ship. ‘Man, that box looks really {adject2}! What’d this clown order again?’ Yelled out Bender, making no move to help with the box despite his comment. Fry and {charaName} set the package down with a grunt. ‘Good news everyone!” Professor Farnsworth called out, holding up a very strange looking device. ‘You’ll be making a delivery to the {noun1} System today, which is filled to the brim with terrible and deadly creatures that evolved from radioactive {noun2}! Luckily, I whipped up this device to repel any monster attacks by emitting a signal that only these monsters can hear.’ He concludes, slapping on the device that looked like a {noun3} to the front of the ship. Upon being attached to the ship, Bender’s antennae starts vibrating at an extremely high speed. ‘Wo-oo-oaa-aah’ is all Bender can say in surprise as his entire body starts to vibrate. ‘Robots can detect the frequency too, but since you don’t have organs to liquidate it shouldn’t be a problem.” the Professor thinks aloud to himself before shrugging and exiting the room. As the bright {color1} ship glided into a clearing on the planet {noun1}, the device did indeed do its job. Any and all dangerous radioactive monsters in the area immediately imploded upon the ship landing, so the crew was met with nothing but silence and the smell of {noun4}. “Ewww, it smells like {noun4} here! Let’s hurry up and deliver this stupid box.” Bender complained, this time grabbing the box and carrying it with ease. Since he was still vibrating though, the box started to vibrate along with him and emit a strange sound that sounded a lot like {adject3} {noun5}. “Hey! What’s the box doing?” Fry asked as Bender and the very {adject2} box started to vibrate at an even higher frequency. The frequency was too high, and both the box and the robot started to vibrate through the surface of the planet. Goo-ooii-iing too-oo-oo fa-aa-st!’ Bender cried out before phasing through the ground with the box. Bender landed on a {adject4} tile surface with a resounding {onomat1}. He picked himself up and grabbed the {adject2} box, both of which had stopped vibrating at a high frequency. ‘Woah, I guess I ended up in some sorta underground passageway.’ he commented while he started wandering around the {adject5} halls. As he walked down the corridor, eventually he came upon a room illuminated by a bright {color2} light. As he entered, a voice responded ‘Oh! You have delivered my box of {noun6} to me! Thank you! I was worried you would have trouble finding me through the Labyrinth of {noun7}. You know, I built it myself.’ Bender set down the box and shrugged. 'Eh, it was nothin’.’";
        }
        
    }
}